name: build and deploy this React app

on: 
    push:
        branches:
            - main
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 20
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: Save build artifact
              uses: actions/upload-artifact@v4
              with:
                  name: dist
                  path: dist

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download build artifact
              uses: actions/download-artifact@v4
              with:
                  name: dist
                  path: dist
            - name: Upload to S3 bucket
              uses: shallwefootball/s3-upload-action@master
              with:
                aws_key_id: ${secrets.AWS_ACCESS_KEY_ID}
                aws_secret_access_key: ${secrets.AWS_SECRET_ACCESS_KEY}
                aws_bucket: pokemon-app-upgraded
                source_dir: dist
                destination_dir: ''

   
