name: build and deploy this React app

on: 
    push:
        branches:
            - main
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 20
            - name: Install dependencies
              run: npm clean install
            - name: Build
              run: npm run build
   
