name: push docker image to aws ecr

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Aws Credentials configuration
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
                aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
                aws-region: us-east-1
            
            - name: Login to ecr
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1
            
            - name: Build, and push image to ecr
              env:
                ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
                ECR_REPOSITORY: "pokemon-api-frontend"
                IMAGE_TAG: latest-${{ github.run_number }}
              run: |
                docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . 
                docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG